services:
  shm-client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      # API http or fastcgi
      # - API=fastcgi
      # SHM_URL http://api if API=http 
      # or SHM_URL=http://core if API=fastcgi
      - SHM_URL=http://core
      # Optional: custom base path (e.g., /client)
      # - SHM_BASE_PATH=/
      # - TELEGRAM_BOT_NAME=your_bot
      # - TELEGRAM_BOT_AUTH_ENABLE=true
      # - SUPPORT_LINK=https://t.me/your_support_bot
      # - TELEGRAM_WEBAPP_AUTH_ENABLE=true
      # - TELEGRAM_WEBAPP_AUTO_AUTH_ENABLE=true
      # - TELEGRAM_WEBAPP_PROFILE=telegram_bot
    depends_on:
      # core or api (docker service name)
      - core
    restart: unless-stopped
