server {
    listen       80;
    server_name  localhost;
    absolute_redirect off;

    charset utf8;
    client_max_body_size 10M;

    set_real_ip_from    0.0.0.0/0;
    real_ip_header      X-Forwarded-For;
    real_ip_recursive   on;

    location / {
        alias /app/;
        try_files $uri $uri/ /index.html;
    }

    location /shm {
        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass #SHM_URL;
        #proxy_cookie_path;
    }

    error_page  404              /index.html;
}
