server {
    listen       80;
    server_name  localhost;
    absolute_redirect off;

    charset utf8;
    client_max_body_size 10M;

    set_real_ip_from    0.0.0.0/0;
    real_ip_header      X-Forwarded-For;
    real_ip_recursive   on;

    location / {
        alias /app/;
        try_files $uri $uri/ /index.html;
    }

    location ~* /config\.js$ {
        alias /app/config.js;
        add_header Cache-Control "no-cache, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    #BASE_LOCATION

    location /docs/ {
        alias /app/docs/;
        add_header Content-Disposition "inline";
    }

    location ~* ^/shm/v1/admin {
        return 403;
    }

    location /shm {
        if ($request_uri ~ /shm/healthcheck\.cgi) {
            access_log off;
        }

        proxy_read_timeout 300s;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_ssl_server_name on;
        proxy_pass #SHM_URL;
        #proxy_cookie_path;
    }

}
